name: ci 

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.INPUT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.INPUT_DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.INPUT_DOCKERHUB_USERNAME }}/topdocapi:latest
        
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
              docker container stop topdocapi
              docker container rm topdocapi
              docker rmi ${{ secrets.DOCKERHUB_USERNAME}}/topdocapi:latest
              echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.INPUT_DOCKERHUB_USERNAME }} --password-stdin
              docker run -e 'NAME_DATABASE=${{ secrets.NAME_DATABASE }}' \
                                                          'HOST_DATABASE=${{ secrets.INPUT_HOST_DATABASE}}' \
                                                          'PASS_DATABASE=${{ secrets.INPUT_PASS_DATABASE}}' \
                                                          'HOST_DATA=${{ secrets.INPUT_HOST_DATA}}' \
                                                          'PORT=${{ secrets.INPUT_PORT}}' \
              -p 5005:5005 --name="topdocapi" ${{ secrets.INPUT_DOCKERHUB_USERNAME}}/topdocapi:latest


        