name: ci 

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Chekcout
        uses: actions/chekckout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/build-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/topDoc:latest
        
      - name: topDoc
        run : echo 'Hello topDoc'
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
              cd ~/projets/demo1/gaet/hello-action
              pwd
              git pull origin master
              git status
              npm install
              docker container stop topDoc
              docker container rm topDoc
              DOCKER_BUILDKIT=1 docker build -t topDoc .
              docker run -dp 3000:3000 --name="topDoc" -e 'NAME_DATABASE=${{ secrets.NAME_DATABASE }}' \
                                                          'HOST_DATABASE=${{ secrets.HOST_DATABASE}}' \
                                                          'PASS_DATABASE=${{ secrets.PASS_DATABASE}}' \
                                                          'HOST_DATA=${{ secrets.HOST_DATA}}' \
                                                          'PORT=${{ secrets.PORT}}'
                                                          topDoc


        